
name: Display (Full) Summary

on:
  push:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Add job Summary
        run: |
          cat << EOF >> $GITHUB_STEP_SUMMARY
          Hello World Job Summary :rocket: !
          EOF
      - name: Add Third Summary
        run: |
          cat << EOF >> $GITHUB_STEP_SUMMARY
          | | Name | Duration | Status| Browser| Platform| Device |
          | --- | --- | --- | --- | --- | --- | --- |
          | :white_check_mark: | [Firefox in sauce](#90517fbac7d14cdbb42742742e427bf5) | 35s | passed | firefox 112 | Windows 10 | |
          | :white_check_mark: | [Chrome in sauce](#76b27eb63654448cabcc9263c50f0332) | 48s | passed | chrome 112 | macOS 11.00 | |
          | :white_check_mark: | [iOS Test](#4bd4fbf0e2e34541bb53393f717ba308) | 1m9s | passed | safari 14.3 | iOS 14.3 | iPhone 12 Simulator |
          | :white_check_mark: | [iOS Test](#c9b41088d57349eb842fe434345a5893) | 1m23s | passed | safari 14.3 | iOS 14.3 | iPad mini (5th generation) Simulator |

          :white_check_mark:    All suites have passed in 1m24s


          Build Link: https://app.saucelabs.com/builds/vdc/0f5aae70bbca3578b41a2dc9dc8c73e9

          ## Job Details

          ### [Firefox in sauce][90517fbac7d14cdbb42742742e427bf5]

          Link: https://app.saucelabs.com/tests/90517fbac7d14cdbb42742742e427bf5

          <details>
            <sumamry>video</Summary>
            <video src="https://assets.saucelabs.com/jobs/90517fbac7d14cdbb42742742e427bf5/video.mp4" controls="controls" style="max-width: 730px;"></video>
          </details>

          <details>
            <summary>Console</summary>

          \`\`\`
          Sauce TestCafe Runner 2.4.0
          Running TestCafe 2.3.1
          Preparing npm environment
          Running tests in:
          - Firefox 112.0 / Windows 10

          √ Getting Started Sauce demo - SwagLabs username not set


          1 passed (3s)
          \`\`\`
          </details>

          ### [Chrome in sauce][76b27eb63654448cabcc9263c50f0332]

          Link: https://app.saucelabs.com/tests/76b27eb63654448cabcc9263c50f0332

          <details>
            <sumamry>video</Summary>
            <video src="https://assets.saucelabs.com/jobs/76b27eb63654448cabcc9263c50f0332/video.mp4" controls="controls" style="max-width: 730px;"></video>
          </details>

          <details>
            <summary>Console</summary>

          \`\`\`
          Sauce TestCafe Runner 2.4.0
          Running TestCafe 2.3.1
          Preparing npm environment
          Running tests in:
          - Chrome 112.0.0.0 / Big Sur 11

          ✓ Getting Started Sauce demo - SwagLabs username not set


          1 passed (8s)
          \`\`\`
          </details>

          ### [iOS Test][4bd4fbf0e2e34541bb53393f717ba308]

          Link: https://app.saucelabs.com/tests/4bd4fbf0e2e34541bb53393f717ba308

          <details>
            <sumamry>video</Summary>
            <video src="https://assets.saucelabs.com/jobs/4bd4fbf0e2e34541bb53393f717ba308/video.mp4" controls="controls" style="max-width: 730px;"></video>
          </details>

          <details>
            <summary>Console</summary>

          \`\`\`
          Sauce TestCafe Runner 2.4.0
          Running TestCafe 2.3.1
          Preparing npm environment
          Running tests in:
          - Safari 14.0.1 / iOS 14.3

          ✓ Getting Started Sauce demo - SwagLabs username not set


          1 passed (11s)
          \`\`\`
          </details>

          ### [iOS Test][c9b41088d57349eb842fe434345a5893]

          Link: https://app.saucelabs.com/tests/c9b41088d57349eb842fe434345a5893

          <details>
            <sumamry>video</Summary>
            <video src="https://assets.saucelabs.com/jobs/c9b41088d57349eb842fe434345a5893/video.mp4" controls="controls" style="max-width: 730px;"></video>
          </details>

          <details>
            <summary>Console</summary>

          \`\`\`
          Sauce TestCafe Runner 2.4.0
          Running TestCafe 2.3.1
          Preparing npm environment
          Running tests in:
          - Safari 14.0.1 / iOS 14.3

          ✓ Getting Started Sauce demo - SwagLabs username not set


          1 passed (11s)
          \`\`\`
          </details>
          EOF
